name: CI - ot-web
on:
  push:
    branches: [main]
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: node --check app.js
      - run: grep -q "msal-browser" Index.html && grep -q "btn-login" Index.html && grep -q "REDIRECT_URI" app.js
      - run: curl -fsS https://ny0gbkz69g.execute-api.us-east-1.amazonaws.com/api/saludo
